-- ============================================================
-- V1: Baseline schema (Milestone 1B)
--   agents, tools, agent_tool_permissions, agent_tool_permission_actions, audit_logs
--
-- Mirrors the schema previously generated by Hibernate (ddl-auto=update), including
-- the enum CHECK constraint names, so databases created before Flyway can be
-- baselined at version 1 without data loss (spring.flyway.baseline-on-migrate=true).
-- Portable SQL: runs on PostgreSQL and on H2 (tests).
-- ============================================================

CREATE TABLE agents (
    id          UUID                        NOT NULL,
    name        VARCHAR(100)                NOT NULL,
    description VARCHAR(1000),
    status      VARCHAR(20)                 NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT agents_pkey PRIMARY KEY (id),
    CONSTRAINT uk_agents_name UNIQUE (name),
    CONSTRAINT agents_status_check CHECK (status IN ('ACTIVE', 'SUSPENDED', 'REVOKED'))
);

CREATE TABLE tools (
    id          UUID                        NOT NULL,
    name        VARCHAR(100)                NOT NULL,
    description VARCHAR(1000),
    tool_type   VARCHAR(30)                 NOT NULL,
    status      VARCHAR(20)                 NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT tools_pkey PRIMARY KEY (id),
    CONSTRAINT uk_tools_name UNIQUE (name),
    CONSTRAINT tools_status_check CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT tools_tool_type_check CHECK (tool_type IN
        ('FILESYSTEM', 'DATABASE', 'SOURCE_CONTROL', 'HTTP', 'CLOUD_STORAGE', 'SHELL', 'OTHER'))
);

CREATE TABLE agent_tool_permissions (
    id         UUID                        NOT NULL,
    agent_id   UUID                        NOT NULL,
    tool_id    UUID                        NOT NULL,
    enabled    BOOLEAN                     NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT agent_tool_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT uk_agent_tool_permission UNIQUE (agent_id, tool_id),
    CONSTRAINT fk_permission_agent FOREIGN KEY (agent_id) REFERENCES agents (id),
    CONSTRAINT fk_permission_tool FOREIGN KEY (tool_id) REFERENCES tools (id)
);

CREATE TABLE agent_tool_permission_actions (
    permission_id UUID        NOT NULL,
    action        VARCHAR(30) NOT NULL,
    CONSTRAINT agent_tool_permission_actions_pkey PRIMARY KEY (permission_id, action),
    CONSTRAINT fk_permission_action_permission FOREIGN KEY (permission_id) REFERENCES agent_tool_permissions (id),
    CONSTRAINT agent_tool_permission_actions_action_check CHECK (action IN
        ('READ', 'WRITE', 'DELETE', 'EXECUTE', 'EXTERNAL_REQUEST'))
);

CREATE TABLE audit_logs (
    id                   UUID                        NOT NULL,
    request_id           UUID                        NOT NULL,
    agent_id             VARCHAR(255)                NOT NULL,
    session_id           VARCHAR(255)                NOT NULL,
    tool                 VARCHAR(255)                NOT NULL,
    action               VARCHAR(255)                NOT NULL,
    resource             VARCHAR(1024)               NOT NULL,
    resource_sensitivity VARCHAR(255)                NOT NULL,
    decision             VARCHAR(255)                NOT NULL,
    risk_score           INTEGER                     NOT NULL,
    reason               VARCHAR(1000),
    action_outcome       VARCHAR(255)                NOT NULL,
    registered_agent_id  UUID,
    registered_tool_id   UUID,
    authorization_result VARCHAR(30),
    authorization_reason VARCHAR(1000),
    timestamp            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
    CONSTRAINT audit_logs_action_check CHECK (action IN
        ('READ', 'WRITE', 'DELETE', 'EXECUTE', 'EXTERNAL_REQUEST')),
    CONSTRAINT audit_logs_action_outcome_check CHECK (action_outcome IN ('ALLOWED', 'BLOCKED', 'REVIEW_REQUIRED')),
    CONSTRAINT audit_logs_decision_check CHECK (decision IN ('ALLOW', 'REVIEW', 'DENY')),
    CONSTRAINT audit_logs_resource_sensitivity_check CHECK (resource_sensitivity IN
        ('PUBLIC', 'INTERNAL', 'SENSITIVE', 'CRITICAL')),
    CONSTRAINT audit_logs_authorization_result_check CHECK (authorization_result IN
        ('AUTHORIZED', 'UNAUTHORIZED', 'AGENT_NOT_FOUND', 'AGENT_SUSPENDED', 'AGENT_REVOKED',
         'TOOL_NOT_FOUND', 'TOOL_DISABLED', 'PERMISSION_DISABLED'))
);
